name: Notificar Status da PR

on:
  pull_request:
    types: [opened, closed]

env: # <-- ENV GLOBAL (vÃ¡lido para todos os jobs e steps)
  TOKEN: ${{ secrets.JWT_TOKEN }}
  URL: ${{ secrets.URL_API }}
  GROUP: ${{ secrets.GROUP }}
  EVENT_NAME: ${{ github.event_name }}
  ACTION: ${{ github.event.action }}
  PR_TITLE: ${{ github.event.pull_request.title || '' }}
  PR_HTML_URL: ${{ github.event.pull_request.html_url || '' }}
  PR_USER_LOGIN: ${{ github.event.pull_request.user.login || '' }}
  PR_MERGED_BY_LOGIN: ${{ github.event.pull_request.merged_by.login || '' }}
  PR_HEAD_REF: ${{ github.event.pull_request.head.ref || '' }}
  PR_BASE_REF: ${{ github.event.pull_request.base.ref || '' }}
  PR_MERGED: ${{ github.event.pull_request.merged || false }}

jobs:
  notify_opened:
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: Notificar PR aberta
        run: |
          curl -X POST "$URL" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $TOKEN" \
            -H "x-github-event: $EVENT_NAME" \
            -d '{
              "group": "'"$GROUP"'",
              "action": "'"$ACTION"'",
              "pull_request": {
                "title": "'"$PR_TITLE"'",
                "html_url": "'"$PR_HTML_URL"'",
                "user": {
                  "login": "'"$PR_USER_LOGIN"'"
                },
                "merged_by": {
                  "login": "'"$PR_MERGED_BY_LOGIN"'"
                },
                "head": {
                  "ref": "'"$PR_HEAD_REF"'"
                },
                "base": {
                  "ref": "'"$PR_BASE_REF"'"
                },
                "merged": '$PR_MERGED'
              }
            }'

  notify_merged:
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Notificar PR mergeada
        run: |
          curl -X POST "$URL" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $TOKEN" \
            -H "x-github-event: $EVENT_NAME" \
            -d '{
              "group": "'"$GROUP"'",
              "action": "'"$ACTION"'",
              "pull_request": {
                "title": "'"$PR_TITLE"'",
                "html_url": "'"$PR_HTML_URL"'",
                "user": {
                  "login": "'"$PR_USER_LOGIN"'"
                },
                "merged_by": {
                  "login": "'"$PR_MERGED_BY_LOGIN"'"
                },
                "head": {
                  "ref": "'"$PR_HEAD_REF"'"
                },
                "base": {
                  "ref": "'"$PR_BASE_REF"'"
                },
                "merged": '$PR_MERGED'
              }
            }'
